Copyright **`(c)`** 2024 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free under certain conditions — see the [`license`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.

In [6]:
from itertools import product
import pandas as pd
import numpy as np

from icecream import ic

In [89]:
cities = pd.read_csv('cities/italy.csv', header=None, names=['name', 'x', 'y'])
cities

                     name      x      y
0                  Ancona  43.60  13.50
1                  Andria  41.23  16.29
2                    Bari  41.12  16.87
3                 Bergamo  45.70   9.67
4                 Bologna  44.50  11.34
5                 Bolzano  46.50  11.35
6                 Brescia  45.55  10.22
7                Cagliari  39.22   9.10
8                 Catania  37.50  15.08
9                 Ferrara  44.84  11.61
10               Florence  43.78  11.24
11                 Foggia  41.47  15.55
12                  Forlì  44.22  12.03
13                  Genoa  44.42   8.93
14  Giugliano in Campania  40.93  14.19
15                 Latina  41.47  12.89
16                Leghorn  43.55  10.30
17                Messina  38.19  15.55
18                  Milan  45.47   9.17
19                 Modena  44.65  10.92
20                  Monza  45.58   9.27
21                 Naples  40.85  14.27
22                 Novara  45.45   8.62
23                  Padua  45.41  11.87
24                Palermo  38.12  13.36
25                  Parma  44.81  10.32
26                Perugia  43.11  12.39
27                Pescara  42.46  14.21
28               Piacenza  45.06   9.68
29                  Prato  43.89  11.09
30                Ravenna  44.42  12.21
31     Reggio di Calabria  38.11  15.65
32     Reggio nell'Emilia  44.71  10.63
33                 Rimini  44.06  12.57
34                   Rome  41.89  12.50
35                Salerno  40.68  14.77
36                Sassari  40.73   8.56
37               Syracuse  37.07  15.29
38                Taranto  40.48  17.24
39                  Terni  42.57  12.65
40                 Trento  46.08  11.12
41                Trieste  45.65  13.77
42                  Turin  45.08   7.68
43                 Venice  45.43  12.33
44                 Verona  45.44  10.99
45                Vicenza  45.55  11.54

In [90]:
dist_matrix = np.zeros((len(cities), len(cities)))
for a, b in product(cities.iterrows(), repeat=2):
    dist_matrix[a[0], b[0]] = (
        ((a[1]['x'] - b[1]['x']) ** 2 + (a[1]['y'] - b[1]['y']) ** 2) ** 0.5
        if a[0] != b[0]
        else np.inf
    )
city_names = np.array([c['name'] for _, c in cities.iterrows()])

In [91]:
visited = np.full(len(cities), False)
dist = dist_matrix.copy()
city = 0
visited[city] = True
tsp = list()
tsp.append(int(city))
while not np.all(visited):
    dist[:, city] = np.inf
    closest = np.argmin(dist[city])
    print(
        f"{city} \"{city_names[city]}\" -> {closest} \"{city_names[closest]}\" ({dist_matrix[city,closest]})"
    )
    visited[closest] = True
    city = closest
    tsp.append(int(city))
print(
    f"{tsp[-1]} \"{city_names[tsp[-1]]}\" -> {tsp[0]} \"{city_names[tsp[0]]}\" ({dist_matrix[tsp[-1],tsp[0]]})"
)
tsp.append(tsp[0])
ic(tsp)
None

0 "Ancona" -> 33 "Rimini" (1.0375451797391766)
33 "Rimini" -> 30 "Ravenna" (0.5091168824543134)
30 "Ravenna" -> 12 "Forlì" (0.26907248094147734)
12 "Forlì" -> 4 "Bologna" (0.7446475676452586)
4 "Bologna" -> 9 "Ferrara" (0.4341658669218506)
9 "Ferrara" -> 23 "Padua" (0.6264982043070771)
23 "Padua" -> 45 "Vicenza" (0.3584689665786987)
45 "Vicenza" -> 44 "Verona" (0.5608921464952051)
44 "Verona" -> 40 "Trento" (0.6530696746902283)
40 "Trento" -> 5 "Bolzano" (0.4788527957525169)
5 "Bolzano" -> 43 "Venice" (1.450965195998857)
43 "Venice" -> 41 "Trieste" (1.4567086187704108)
41 "Trieste" -> 26 "Perugia" (2.89067466173556)
26 "Perugia" -> 39 "Terni" (0.599332962550867)
39 "Terni" -> 34 "Rome" (0.6963476143421472)
34 "Rome" -> 15 "Latina" (0.5731491952362857)
15 "Latina" -> 14 "Giugliano in Campania" (1.4076931483814206)
14 "Giugliano in Campania" -> 21 "Naples" (0.11313708498984645)
21 "Naples" -> 35 "Salerno" (0.5281098370604363)
35 "Salerno" -> 11 "Foggia" (1.110180165558726)
11 "Foggia" -> 1 "Andria" (0.7779460135510681)
1 "Andria" -> 2 "Bari" (0.5903388857258194)
2 "Bari" -> 38 "Taranto" (0.7392563831310498)
38 "Taranto" -> 17 "Messina" (2.846085030353099)
17 "Messina" -> 31 "Reggio di Calabria" (0.12806248474865564)
31 "Reggio di Calabria" -> 8 "Catania" (0.8348652585896719)
8 "Catania" -> 37 "Syracuse" (0.4785394445602153)
37 "Syracuse" -> 24 "Palermo" (2.1971344974762)
24 "Palermo" -> 7 "Cagliari" (4.399727264274458)
7 "Cagliari" -> 36 "Sassari" (1.6036520819679039)
36 "Sassari" -> 16 "Leghorn" (3.3136083051561784)
16 "Leghorn" -> 29 "Prato" (0.8600581375697814)
29 "Prato" -> 10 "Florence" (0.18601075237738268)
10 "Florence" -> 19 "Modena" (0.9269843580125804)
19 "Modena" -> 32 "Reggio nell'Emilia" (0.29614185789921654)
32 "Reggio nell'Emilia" -> 25 "Parma" (0.3257299494980475)
25 "Parma" -> 28 "Piacenza" (0.6870953354520759)
28 "Piacenza" -> 3 "Bergamo" (0.640078120232211)
3 "Bergamo" -> 20 "Monza" (0.4176122603564236)
20 "Monza" -> 18 "Milan" (0.1486606874731844)
18 "Milan" -> 22 "Novara" (0.5503635162326793)
22 "Novara" -> 42 "Turin" (1.010198000393985)
42 "Turin" -> 13 "Genoa" (1.4135416513141719)
13 "Genoa" -> 6 "Brescia" (1.7149344010777765)
6 "Brescia" -> 27 "Pescara" (5.046602817737886)
27 "Pescara" -> 0 "Ancona" (1.3430189872075533)

ic| tsp: [0,
          33,
          30,
          12,
          4,
          9,
          23,
          45,
          44,
          40,
          5,
          43,
          41,
          26,
          39,
          34,
          15,
          14,
          21,
          35,
          11,
          1,
          2,
          38,
          17,
          31,
          8,
          37,
          24,
          7,
          36,
          16,
          29,
          10,
          19,
          32,
          25,
          28,
          3,
          20,
          18,
          22,
          42,
          13,
          6,
          27,
          0]

In [84]:
tot_cost = 0
for c1, c2 in zip(tsp, tsp[1:]):
    tot_cost += dist_matrix[c1, c2]
ic(tot_cost)
None

ic| tot_cost: np.float64(10.424364686600125)